- hosts: 127.0.0.1
  connection: local
  remote_user: root
  become: yes
  ## need to set before running ansible!
  become_user: user_of_local_machine
  roles:
    - mirrors
    - fancy-shell
    - golang

